# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a0d1251234f561694fbea6d6cf5a5d5d9f6559ed12ccb6a07aefc8df19c90fce96fb2a02351768e9d7e40b1303089e538b48cf7c015d9f2cdf4288d374bcb3a

test:
  secret_key_base: 40ddc2e2067d8a74c2e6b3407e52d11e3bae03fea10e35e59f9a397c908111f475023c916112dadacf433970db320ef94a4bae864bd038c45e813e2f04e9ff40

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
